// Generated by Wrangler on Wed Apr 24 2024 21:58:55 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	KINDE_CLIENT_ID: string;
	KINDE_CLIENT_SECRET: string;
	KINDE_ISSUER_URL: string;
	KINDE_SITE_URL: string;
	KINDE_POST_LOGOUT_REDIRECT_URL: string;
	KINDE_POST_LOGIN_REDIRECT_URL: string;
}
